#!/usr/bin/env python
""" Dynamic DynamoDB - Auto provisioning for AWS DynamoDB

APACHE LICENSE 2.0
Copyright 2013-2104 Sebastian Dahlgren

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import sys

import dynamic_dynamodb


if __name__ == '__main__':
    try:
        dynamic_dynamodb.main()
    except KeyboardInterrupt:
        print('')
        sys.exit(0)
    sys.exit(0)

sys.exit(1)
